# This playbook will launch and EC2 with specific configuration of VPC-Subnet-region with public IP enabled
---
- hosts: localhost
  connection: local
  gather_facts: True
  become: True
  vars:
    key_name: eng130
    region: eu-west-1
    image:  ami-046eebc2b6e633a26
    id: "SRE Ansible EC2 18.04"
    sec_group: "eng130_osman_ansible_app1"
    subnet_id: "subnet-0429d69d55dfad9d2"
# add the following line if ansible by default uses python 2.7
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Facts
      block:

      - name: Get instances facts
        ec2_instance_facts:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          region: "{{ region }}"
        register: result


    - name: Provisioning EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"


      - name: Provision instance(s)
        ec2:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          assign_public_ip: true
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          vpc_subnet_id: "{{ subnet_id }}"
          group_id: "{{ sec_group }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
          instance_tags:
            Name: eng130_osman_node_app_from_ansible1

      tags: ['never', 'create_ec2']
---
- hosts: localhost
  connection: local
  gather_facts: True
  become: True
  vars:
    key_name: eng130
    region: eu-west-1
    image: ami-046eebc2b6e633a26
    id: "eng130_osman_ansible_app"
    security_group_id: "sg-012fba9c5909d8e1b"
    subnet_id: "subnet-0429d69d55dfad9d2"
    ansible_python_interpreter: /usr/bin/python3


     - name: Get instances facts
       ec2_instance_facts:
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         region: "{{ region }}"
       register: result


   - name: Provisioning EC2 instances
     block:

     - name: Upload public key to AWS
       ec2_key:
         name: "{{ key_name }}"
         key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
         region: "{{ region }}"
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"



     - name: Provision instance(s)
       ec2:
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         assign_public_ip: true
         key_name: "{{ key_name }}"
         id: "{{ id }}"
         vpc_subnet_id: "{{ subnet_id }}"
         group_id: "{{ security_group_id }}"
         image: "{{ image }}"
         instance_type: t2.micro
         region: "{{ region }}"
         wait: true
         count: 1
         instance_tags:
           Name: eng130_osman_node_app_from_ansible



     tags: ['never', 'create_ec2']


